include: package:flutter_lints/flutter.yaml

analyzer: 
  exclude: [lib/**.g.dart, lib/**.freezed.dart, lib/**.config.dart]
  errors: 
    invalid_annotation_target: ignore
    depend_on_referenced_packages: ignore

linter:
  rules: