name: papay
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  google_sign_in: ^5.3.2
  auto_route: ^4.0.1
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  google_fonts: ^3.0.1
  injectable: ^1.5.3
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.5.3+1
  uuid: ^3.0.6
  font_awesome_flutter: ^10.1.0
  shimmer: ^2.0.0
  dropdown_button2: ^1.5.2
  flutter_osm_plugin: ^0.34.0+1
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  auto_route_generator: ^4.0.0
  json_serializable: ^6.2.0
  injectable_generator: ^1.5.3
  
flutter:
  uses-material-design: true
