// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3p00n-heOKhsPXfF_nqhBYRiTNYKODkE',
    appId: '1:128487887909:web:ecc27421718f901b661bcc',
    messagingSenderId: '128487887909',
    projectId: 'papay---pay--n-play',
    authDomain: 'papay---pay--n-play.firebaseapp.com',
    storageBucket: 'papay---pay--n-play.appspot.com',
    measurementId: 'G-9CZKCG020R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL35VNbk7nhqlvQm_zSpyKDrjWAnaslDc',
    appId: '1:128487887909:android:f5ffa33f6bce3328661bcc',
    messagingSenderId: '128487887909',
    projectId: 'papay---pay--n-play',
    storageBucket: 'papay---pay--n-play.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRMk-YjE569ZaovEvwaQ3OiZo5If2Hi8',
    appId: '1:128487887909:ios:84158860d37ff931661bcc',
    messagingSenderId: '128487887909',
    projectId: 'papay---pay--n-play',
    storageBucket: 'papay---pay--n-play.appspot.com',
    iosClientId: '128487887909-e8sp99bbb13gb49nh1ded187ja2bv5rs.apps.googleusercontent.com',
    iosBundleId: 'com.papay.app.papay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmRMk-YjE569ZaovEvwaQ3OiZo5If2Hi8',
    appId: '1:128487887909:ios:84158860d37ff931661bcc',
    messagingSenderId: '128487887909',
    projectId: 'papay---pay--n-play',
    storageBucket: 'papay---pay--n-play.appspot.com',
    iosClientId: '128487887909-e8sp99bbb13gb49nh1ded187ja2bv5rs.apps.googleusercontent.com',
    iosBundleId: 'com.papay.app.papay',
  );
}
